services:
  backupify:
    build: .
    container_name: backupify
    network_mode: host  # This makes the container use the host's network
    environment:
      - BACKUP_SCHEDULE=daily # every_2_days , weekly , monthly
      - SITE_NAME=wordpress
      - WP_DIR=/opt/www/html #Dont Change
      - DB_NAME=wlwordpressdb
      - DB_USER=root
      - DB_HOST=127.0.0.1  # This can now point to the host machine's MySQL
      - DB_PORT=3306
      - DB_PASSWORD=wladmin@123+
      - MAX_BACKUPS=7
      - INCLUDE_DB=yes
      - BOT_TOKEN=7922034172:AAH2_elDK8LSd-IS5RqjZhMLXfIqVWENUBM
      - CHAT_IDS=5139800235
    volumes:
      - /home/wladmin/Documents/GitHub/wordpress/opt/www/wordpress:/opt/www/html
      - ./backups:/opt/www/backups
    restart: unless-stopped
